### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by ivangretsky** [zurb/foundation-sites-template#1]
Good day!
The repo does not have readme, so it is not clear, what it does and if it is recommended to use. Can you please answer a few meta questions below?
* Is it the official starting point for foundation with libsass and gulp projects? Something like foundation-libsass-template for libsass and grunt?
* Is it recommended to use?
* Will it be upgraded/supported?
* What is "Sites" project  - I could not find any info on this. Is it regular Foundation, but in contrast to new email and app variations?
I was looking for starting point to use Foundation with gulp an libsass. No info on that on offsite (http://foundation.zurb.com/docs/sass.html).

Thank you.

**Comment by gakimball** [comment]
This is a template project for Foundation 6, which is still being developed. It's a Node-based template that compiles Sass via node-sass/Gulp. It's one of two starter projects that will be distributed with Foundation 6; the other one is an "advanced" template that also handles JS compression, image compression, and Handlebars templating.

So for now, although the template pretty much works, it's not recommended that anyone use it at this time.

**Comment by ivangretsky** [comment]
Sorry to continue on this, but is there a recommended starting point for libsass+gulp+foundation 5?

**Comment by gakimball** [comment]
We have a Grunt-based template, but not a Gulp one. <https://github.com/zurb/foundation-libsass-template>
